---

- name: Service tasks
  become: true
  tags:
    - nfs_client
    - nfs_client_service
  block:
    - name: Manage service
      when: not ansible_check_mode
      ansible.builtin.service:
        name: "{{ nfs_client_service_name }}"
        state: "{{ nfs_client_service_ensure }}"
        enabled: "{{ nfs_client_service_enable }}"
